# Generated by Django 4.2.7 on 2024-12-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0002_proyect_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyect',
            name='members',
            field=models.CharField(default='default_rut', max_length=255),
        ),
    ]
